// Generated by Femboy Language Compiler

const io = { print: (...args) => console.log(...args) };

const utils$helper = (() => {
    const __exports = {};
    let greet = ((name) => {
        io.print("Hello from utils, dear", name);
    });
    __exports.greet = greet;
    let add = ((a, b) => (a + b));
    __exports.add = add;
    return __exports;
})();

const utils = { helper: utils$helper };
let main = (() => {
    utils.helper.greet("World");
    let result = utils.helper.add(2, 3);
    io.print("2 + 3 =", result);
});
main();
