// Generated by Femboy Language Compiler

const io = { print: (...args) => console.log(...args) };

let hellow_world = "hellow world";
let global_var = 5;
class Human {
    name = "";
    #privateAge = 0;
    constructor(age) {
        this.#privateAge = age;
    }
    talk() {
        io.print("Hi, I am", this.name);
    }
}
class Cutie extends Human {
    constructor(age) {
        super(age);
    }
    talk(age) {
        super.talk();
        io.print("...and I am cute!");
    }
}
let newHuman = ((age) => new Human(age));
let main = (() => {
    let lst = [1, "okak"];
    for (const x of lst) {
        io.print(x);
    }
    let i = 0;
    while ((i < 5)) {
        i += 1;
    }
    let alwaysTrue = true;
    if (alwaysTrue) {
        io.print("true branch");
    } else if ((!alwaysTrue)) {
        io.print("else if branch");
    } else {
        io.print("else branch");
    }
    let range = Array.from({length: (3) - (0)}, (_, i) => i + (0));
    io.print("My bf said:", hellow_world);
    io.print("Range:", range);
    io.print("Difficult command:", (() => "hello world")());
    let h = new Cutie(18);
    h.name = "Alex";
    h.talk();
});
main();
