// Generated by Femboy Language Compiler

const io = { print: (...args) => console.log(...args) };

let jsAlert = ((message) => {
    let result;
    (() => {
		// Pure JS code here
		result = String(message).toUpperCase()
	})();
    return result;
});
let varargFn = ((first, ...rest) => {
    io.print("First:", first);
    for (const item of rest) {
        io.print("Rest item:", item);
    }
});
let main = (() => {
    let upper = jsAlert("hello native");
    io.print("Native result:", upper);
    varargFn("one", "two", "three", "four");
});
main();
